Stubs to get it work with a regular JRE 8 Not a good idea, so
openjdk version "1.8.0_322"
IBM Semeru Runtime Open Edition (build 1.8.0_322-b06)
Eclipse OpenJ9 VM (build master-60b276f2f, JRE 1.8.0 Linux aarch64-64-Bit 20220313_000000 (JIT enabled, AOT enabled)
OpenJ9   - unknown
OMR      - ac9454477
JCL      - unknown based on unknown)
Exception in thread "Attach API initializer" java.lang.NoClassDefFoundError: com.ibm.oti.util.Msg (initialization failure)
        at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:95)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:867)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:861)
        at java.lang.Thread.uncaughtException(Thread.java:1343)
Caused by: java.lang.UnsatisfiedLinkError: java/util/zip/ZipFile.getManifestNum(J)I
        at java.util.zip.ZipFile.<init>(ZipFile.java:234)
        at java.util.zip.ZipFile.<init>(ZipFile.java:157)
        at java.util.jar.JarFile.<init>(JarFile.java:171)
        at java.util.jar.JarFile.<init>(JarFile.java:108)
        at com.ibm.oti.vm.AbstractClassLoader.fillCache(AbstractClassLoader.java:84)
        at com.ibm.oti.vm.AbstractClassLoader.getResourceAsStream(AbstractClassLoader.java:312)
        at com.ibm.oti.vm.MsgHelp.loadMessages(MsgHelp.java:184)
        at com.ibm.oti.util.PriviAction.run(PriviAction.java:172)
        at java.security.AccessController.doPrivileged(AccessController.java:682)
        at com.ibm.oti.util.Msg.<clinit>(Msg.java:63)
        at openj9.internal.tools.attach.target.CommonDirectory.openSemaphore(CommonDirectory.java:240)
        at openj9.internal.tools.attach.target.AttachHandler.createFiles(AttachHandler.java:205)
        at openj9.internal.tools.attach.target.AttachHandler.initialize(AttachHandler.java:298)
        at openj9.internal.tools.attach.target.AttachHandler.run(AttachHandler.java:231)